### ISSUE TITLE
I am hoping to obtain the HER2 dataset that was used in the code

### ISSUE THREAD

**Issue by zwtzzyuss** [DIDSR/DomId#1]
Hello, I was wondering if you could possibly share the dataset used for HER2 in the article? I would greatly appreciate it. Thank you very much.

**Comment by agisga** [comment]
Thank you for your message and interest in our work. I understand the importance of data in advancing our field, but unfortunately, I am not in a position to share this particular dataset due to specific restrictions that it is subject to.

**Comment by zwtzzyuss** [comment]
Thanks for your reply, can I get an idea of the file structure of your HER2 dataset, I am a student who needs to understand and reproduce this paper

**Comment by agisga** [comment]
> Thanks for your reply, can I get an idea of the file structure of your HER2 dataset, I am a student who needs to understand and reproduce this paper

The file structure, as it goes into our clustering models (as they are implemented in this repository), is that we have directories corresponding to the different HER2 classes (1, 2, 3), which contain image patches in .tif format. The file names of the image patches contain information about the tissue slide ID and the scanner used. Additionally, there is a .csv file containing the slide IDs and patch IDs for each of the .tif files, as well as the corresponding HER2 grading scores from 7 pathologists. 
Please feel free to let me know if you have any specific questions.

**Comment by zwtzzyuss** [comment]
Thanks for your reply,could you tell me more about the datafame.csv file? I want to know what variables are in it and how they relate to the image data

**Comment by zwtzzyuss** [comment]
I would like to run your program on other publicly available medical image datasets. Could you please suggest some suitable ones?

**Comment by agisga** [comment]
Thank you for your questions. Generally, since the models implemented here are unsupervised, any dataset of images could be used. To apply conditioning like in our MICCAI 2023 paper, you would need additionally some kind of labels that you want to condition the clustering on. 
For example, a public dataset that I have used in the past for a similar but separate project (https://doi.org/10.1117/12.2551346) is the CBIS-DDSM dataset (mammography images), which is publicly available and has annotations for at least masses and microcalcification clusters, malignant vs. benign, breast density category (1-4), digitizer manufacturer (HOWTEK, LUMISYS), and mammographic view (left/CC, left/MLO, right/CC, right/MLO), any of which could be used as the variable to condition on. 

Note that adding a custom dataset, would require to write a dataset class definition and task definition, as for example similar to: https://github.com/DIDSR/DomId/blob/main/domid/dsets/dset_her2.py and  https://github.com/DIDSR/DomId/blob/main/domid/tasks/task_her2.py
We are planning to release additional documentation on how to add custom datasets, tasks, and models to our python package, hopefully within the next week.

If you encounter issues running the code on a specific public dataset, please feel free to open a separate issue about the specific dataset and problem you encounter.

**Comment by zwtzzyuss** [comment]
Hello, could you please provide a detailed explanation of the information inside the dataframe file?

**Comment by agisga** [comment]
> Hello, could you please provide a detailed explanation of the information inside the dataframe file?

In general there are no strict rules on what the dataframe file should look like. It can be different for each specific dataset definition (see my last response mentioning the dataset class definition). To answer your question, the dataframe file used for the HER2 dataset (as used [here](https://github.com/DIDSR/DomId/blob/ed7926b766bede6f4758e76e1b299ddcb922ea83/domid/dsets/dset_her2.py#L42)) looks as follows:

```
img_id,class,machine,score
xxxx.jpg,1,2,28.718144285714285
yyyy.jpg,...,...,...
...,...,...,...
```
